default:
  before_script:
    - echo "Execute this `before_script` in all jobs by default."
  after_script:
    - echo "Execute this `after_script` in all jobs by default."

stages:
  - job

image: alpine

job1:
  stage: job
  script:
    - echo "This is a new version of ubuntu $UBUNTU"
  parallel:
    matrix:
      - UBUNTU: [22, 20, 18]
