stages:
  - change_npm
  - build
  - test
  - deploy

image: alpine

.default_rules:
  rules:
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline"
      when: never

default_conditionnal:
  stage: build
  rules:
    - !reference [.default_rules, rules]
  script:
    - echo "This job builds something else. $CI_PIPELINE_SOURCE"

change_npm:
  stage: build
  rules:
    - changes:
        - fake.packages.json
  script:
    - echo "NPM_INSTALL"

build_b:
  stage: build
  script:
    - echo "This job builds something else. $CI_PIPELINE_SOURCE"

test_b:
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: manual
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline"
  script:
    - echo "This job tests something else."

deploy_b:
  stage: deploy
  script:
    - echo "This job deploys something else."
