name: run-bash-script
on: [push]
jobs:
  example-hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run build script
        run: ./.github/scripts/hello.sh
        shell: bash
